[libraries]
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

[versions]
inject = "1"
coroutines = "1.7.3"
junit4 = "4.13.2"
coroutines-test = "1.6.4"